@baseUrl = http://localhost:3000

######### USER OPERATIONS ###########

### Register a new user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword"
}

### Login with the new user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword"
}

### Save the JWT token from the login response
@jwtToken = <your_jwt_token_here>

### Login with an incorrect password
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "newuser",
    "password": "wrongpassword"
}

######### FILM OPERATIONS ###########

### Read all films
GET {{baseUrl}}/films

### Read all films with minimum duration
GET {{baseUrl}}/films?minimum-duration=120

### Read a single film
GET {{baseUrl}}/films/1

### Create a film (requires JWT)
POST {{baseUrl}}/films
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "The Godfathers",
    "director": "Francis Ford Coppola",
    "duration": 175,
    "budget": 6000000,
    "description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "imageUrl": "http://example.com/godfathers.jpg"
}

### Try to create a film with incomplete data (requires JWT)
POST {{baseUrl}}/films
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "Incomplete Film",
    "director": "Unknown Director"
}

### Update a film (requires JWT)
PATCH {{baseUrl}}/films/1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "Inception Updated",
    "duration": 150
}

### Delete a film (requires JWT)
DELETE {{baseUrl}}/films/1
Authorization: Bearer {{jwtToken}}

######### DRINK OPERATIONS ###########

### Create a drink (requires JWT and admin)
POST {{baseUrl}}/drinks
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Coca Cola",
    "image": "http://example.com/cocacola.jpg",
    "volume": 500,
    "price": 2.5
}

### Delete a drink (requires JWT and admin)
DELETE {{baseUrl}}/drinks/1
Authorization: Bearer {{jwtToken}}